esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

esphome:
  name: ${hostname}
  name_add_mac_suffix: false

i2c:
  sda: GPIO1
  scl: GPIO0
  id: bus_a

uart:
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret fallback_wifi_ssid
    password: !secret fallback_wifi_password
  power_save_mode: LIGHT

web_server:
  port: 80

logger: