esphome:
  name: ${hostname}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: esp-idf

i2c:
  sda: GPIO18
  scl: GPIO19
  scan: true

uart:
  tx_pin: GPIO8
  rx_pin: GPIO5
  baud_rate: 115200
  #debug:
  #  direction: BOTH
  #  dummy_receiver: true
  #  after:
  #    delimiter: "\n"
  #  sequence:
  #    - lambda: UARTDebug::log_string(direction, bytes);

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret fallback_wifi_ssid
    password: !secret fallback_wifi_password

network:
  enable_ipv6: false

web_server:
  port: 80

logger:
  hardware_uart: UART0
  baud_rate: 115200