esphome:
  name: ${hostname}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: esp-idf

light:
  - platform: status_led
    id: light_led
    pin: GPIO2

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO3
      mode:
        input: true
        pullup: true
    id: binary_sensor_pir
    filters:
      - delayed_on: 50ms
      - delayed_off: 500ms
  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
    id: binary_sensor_mmwave
    filters:
      - delayed_on: 50ms

i2c:
  sda: GPIO18
  scl: GPIO19
  scan: true

uart:
  tx_pin: GPIO8
  rx_pin: GPIO5
  baud_rate: 115200

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret fallback_wifi_ssid
    password: !secret fallback_wifi_password

network:
  enable_ipv6: false

web_server:
  port: 80

logger:
  hardware_uart: UART0
  baud_rate: 115200