esphome:
  name: ${hostname}
  name_add_mac_suffix: false
  platformio_options:
    board_upload.flash_size: 2MB
    board_upload.maximum_size: 2097152
    board_build.ldscript: eagle.flash.2m.ld

esp8266:
  board: esp8285
  restore_from_flash: true

light:
  - platform: status_led
    id: light_led
    pin: GPIO16

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO14
      mode:
        input: true
        pullup: true
    id: binary_sensor_pir
    filters:
      - delayed_on: 50ms
      - delayed_off: 500ms
  - platform: gpio
    pin:
      number: GPIO12
      mode:
        input: true
        pullup: true
    id: binary_sensor_mmwave
    filters:
      - delayed_on: 50ms

preferences:
  flash_write_interval: 1min

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

uart:
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 115200

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret fallback_wifi_ssid
    password: !secret fallback_wifi_password

network:
  enable_ipv6: false

web_server:
  port: 80

logger:
  baud_rate: 115200

mdns:
  disabled: false