defaults:
  board: esp01_1m

esphome:
  name: ${hostname}
  name_add_mac_suffix: false

esp8266:
  board: ${board}

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret fallback_wifi_ssid
    password: !secret fallback_wifi_password
  power_save_mode: HIGH # for ESP8266 LOW/HIGH are mixed up, esphome/issues/issues/1532

network:
  enable_ipv6: false  

logger: