binary_sensor:
  - platform: status
    name: "${device_type}/${path}/connected"
    entity_category: "diagnostic"

time:
  - platform: homeassistant
    id: ha_time

sensor:
  - platform: uptime
    name: "${device_type}/${path}/uptime"
    type: timestamp
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: "${device_type}/${path}/wifi_rssi"
    filters:
      - delta: 1
    entity_category: "diagnostic"