substitutions:
  path: "bedroom"
  hostname: "apollo-bedroom"

packages:
  hardware: !include hardware/apollo_msr2.yaml
  device: !include 
    file: device/apollo_msr2.yaml
    vars:
      entity_id_ha_helper_mode_sleeping: "input_boolean.helper_mode_bedroom_sleeping"
  beacon: !include device/apollo_msr2.beacon.yaml
  tracking: !include sensors/ibeacon/tracking.all.yaml
  diagnostic: !include sensors/diagnostic.esp32.yaml