substitutions:
  path: "living_room"
  hostname: "apollo-living-room"

packages:
  hardware: !include _hardware.apollo_msr2.yaml
  device: !include _device.apollo_msr2.core_slim.yaml
  beacon: !include _device.apollo_msr2.beacon.yaml
  tracking: !include _ibeacon.tracking.all.yaml


#esp32_ble_tracker:
#   on_ble_advertise:
#    then:
#      - lambda: |-
#          ESP_LOGD("ble_adv", "New BLE device");
#          ESP_LOGD("ble_adv", "  address: %s", x.address_str().c_str());
#          ESP_LOGD("ble_adv", "  name: %s", x.get_name().c_str());
#          ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
#          for (auto uuid : x.get_service_uuids()) {
#              ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
#          }
#          ESP_LOGD("ble_adv", "  Advertised service data:");
#          for (auto data : x.get_service_datas()) {
#              ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
#          }
#          ESP_LOGD("ble_adv", "  Advertised manufacturer data:");
#          for (auto data : x.get_manufacturer_datas()) {
#              ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
#          }