substitutions:
  path: "living_room"
  hostname: "apollo-living-room"

packages:
  hardware: !include hardware/apollo_msr2.yaml
  device: !include device/apollo_msr2.yaml
  beacon: !include device/apollo_msr2.beacon.yaml
  tracking: !include sensors/ibeacon/tracking.all.yaml
  diagnostic: !include sensors/diagnostic.esp32.yaml