substitutions:
  path: "hallway/entrance"
  hostname: "athom-hallway-entrance"

packages:
  hardware: !include hardware/athom_ps_c3.yaml
  device: !include device/athom_ps.yaml
  diagnostic: !include sensors/diagnostic.esp32.yaml