substitutions:
  path: "kitchen/sink"
  hostname: "athom-kitchen-sink"

packages:
  hardware: !include hardware/athom_ps_8285.yaml
  device: !include device/athom_ps.yaml
  diagnostic: !include sensors/diagnostic.yaml