substitutions:
  path: "hallway/strip"
  hostname: "light-hallway-strip"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include 
    file: _device.shelly_rgbw2.yaml
    vars: 
      channel_2_light_name: "inner"
      channel_2_internal: "false"
      channel_4_light_name: "entrance"
      channel_4_internal: "false"