substitutions:
  type: "light_switch"
  path: "bedroom"
  hostname: "light-switch-bedroom"
  relay_1_suffix: "bed"
  relay_2_suffix: "wardrobe"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include _device.gosund_sw9.yaml