substitutions:
  type: "light_switch"
  path: "office"
  hostname: "light-switch-office"
  relay_1_suffix: "back"
  relay_2_suffix: "side"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include 
    file: _device.gosund_sw9.yaml
    vars: 
      left_button_relay: "2"
      right_button_relay: "1"