substitutions:
  path: "hallway/inner"
  mode_id_path: "hallway"
  hostname: "light-switch-hallway-inner"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include 
    file: _device.gosund_sw9.yaml
    vars: 
      relay_1_suffix: "unused_1"
      relay_2_suffix: "unused_2"
  remove_direct_relay_control: !include _feature.gosund_sw9.remove_direct_relay_control.yaml