substitutions:
  type: "light_switch"
  path: "test"
  hostname: "light-switch-test"
  # Relays
  relay_1_suffix: "one"
  relay_2_suffix: "two"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include 
    file: _device.gosund_sw9.yaml
    vars: 
      relay_2_restore_mode: always_off
      right_button_relay: 1

wifi: 
  use_address: "192.168.0.203"