substitutions:
  path: "hallway/entrance"
  mode_id_path: "hallway"
  hostname: "light-switch-hallway-entrance"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include 
    file: _device.gosund_sw9.yaml
    vars: 
      relay_1_suffix: "strip"
      relay_2_suffix: "center"
      left_button_relay: "1"
      right_button_relay: "1"