substitutions:
  type: "light_switch"
  path: "bathroom"
  hostname: "light-switch-bathroom"
  relay_1_suffix: "all"
  relay_2_suffix: "unused"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include 
    file: _device.gosund_sw9.yaml
    vars: 
      left_button_relay: "1"
      right_button_relay: "1"
      relay_2_restore_mode: always_off