substitutions:
  path: "bathroom"
  mode_id_path: "bathroom"
  hostname: "light-switch-bathroom"

packages:
  hardware: !include _hardware.gosund_sw9.yaml
  device: !include 
    file: _device.gosund_sw9.yaml
    vars: 
      relay_1_suffix: "all"
      relay_2_suffix: "unused"
      left_button_relay: "1"
      right_button_relay: "1"