substitutions:
  type: "light_switch"
  path: "test"
  hostname: "light-switch-test"
  relay_1_suffix: "hello"
  relay_2_suffix: "world"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include 
    file: _device.gosund_sw9.yaml
    vars: 
      relay_2_restore_mode: always_off

#wifi: 
#  use_address: "192.168.0.203"