substitutions:
  path: "office"
  mode_id_path: "office"
  hostname: "light-switch-office"

packages:
  hardware: !include _hardware.gosund_sw9.yaml
  device: !include 
    file: _device.gosund_sw9.yaml
    vars:       
      relay_1_suffix: "back"
      relay_2_suffix: "side"
      left_button_relay: "2"
      right_button_relay: "1"