substitutions:
  path: "living_room"
  hostname: "light-switch-living-room"
  relay_1_suffix: "center"
  relay_2_suffix: "spot"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include 
    file: _device.gosund_sw9.yaml
    vars: 
      left_button_relay: "2"
      right_button_relay: "1"