substitutions:
  path: "hallway/entrance"
  hostname: "light-switch-hallway-entrance"
  relay_1_suffix: "strip"
  relay_2_suffix: "center"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include 
    file: _device.gosund_sw9.yaml
    vars: 
      relay_2_restore_mode: always_off