substitutions:
  path: "kitchen"
  hostname: "light-switch-kitchen"
  relay_1_suffix: "spot"
  relay_2_suffix: "center"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include 
    file: _device.gosund_sw9.yaml
    vars: 
      left_button_relay: "2"
      right_button_relay: "1"