substitutions:
  path: "bedroom"
  mode_id_path: "bedroom"
  hostname: "light-switch-bedroom"

packages:
  hardware: !include _hardware.esp8266.yaml
  device: !include
    file: _device.gosund_sw9.yaml
    vars:
      relay_1_suffix: "bed"
      relay_2_suffix: "wardrobe"